Day_07 Matplotlib

Part A — the curriculum activities

In [1]:
# TASK 01
# Statistics along axes, on multi-dimensional data

import numpy as np
import matplotlib.pyplot as plt

# Seed the random generator for reproducible results
rng = np.random.default_rng(42)

# 4 shops × 30 days × 3 product categories
sales = rng.integers(50, 500, size=(4, 30, 3))

print("Original sales shape:", sales.shape)
# Expected: (4, 30, 3)


# ---------------------------------------------------------
# 1. Total sales per shop
# Collapse days (axis=1) and categories (axis=2)
# ---------------------------------------------------------
per_shop = sales.sum(axis=(1, 2))

print("\nTotal sales per shop:")
print(per_shop)
print("Shape:", per_shop.shape)
# Expected: (4,)


# ---------------------------------------------------------
# 2. Average daily sales per category
# Collapse shops (axis=0) and days (axis=1)
# ---------------------------------------------------------
avg_per_category = sales.mean(axis=(0, 1))

print("\nAverage sales per category:")
print(avg_per_category)
print("Shape:", avg_per_category.shape)
# Expected: (3,)


# ---------------------------------------------------------
# 3. Best day for each shop
# First collapse categories, then find the maximum day
# ---------------------------------------------------------
daily_totals = sales.sum(axis=2)

print("\nDaily totals shape:", daily_totals.shape)
# Expected: (4, 30)

best_day = np.argmax(daily_totals, axis=1)

print("Best day for each shop:")
print(best_day)
print("Shape:", best_day.shape)
# Expected: (4,)


# ---------------------------------------------------------
# 4. Most consistent shop
# Calculate standard deviation of daily totals
# ---------------------------------------------------------
daily_std = daily_totals.std(axis=1)

print("\nStandard deviation of daily totals:")
print(daily_std)
print("Shape:", daily_std.shape)
# Expected: (4,)

most_consistent_shop = np.argmin(daily_std)

print("Most consistent shop:", most_consistent_shop + 1)
print("Lowest standard deviation:", daily_std[most_consistent_shop])


# ---------------------------------------------------------
# 5. Mean-centering using keepdims=True
# ---------------------------------------------------------
# Calculate the mean for each shop while keeping dimensions
shop_means = sales.mean(axis=(1, 2), keepdims=True)

print("\nShop means with keepdims=True:")
print(shop_means)
print("Shape:", shop_means.shape)
# Expected: (4, 1, 1)

# Mean-center the original sales data
centered_sales = sales - shop_means

print("\nMean-centered sales shape:")
print(centered_sales.shape)
# Expected: (4, 30, 3)

# Verify that each shop's centered mean is approximately zero
centered_means = centered_sales.mean(axis=(1, 2))

print("\nMean of centered sales for each shop:")
print(centered_means)
# Expected: values very close to 0

Original sales shape: (4, 30, 3)

Total sales per shop:
[25751 24730 24062 24356]
Shape: (4,)

Average sales per category:
[274.625      277.76666667 271.76666667]
Shape: (3,)

Daily totals shape: (4, 30)
Best day for each shop:
[15 23  7 25]
Shape: (4,)

Standard deviation of daily totals:
[177.53543934 205.11303117 191.27239448 223.6727868 ]
Shape: (4,)
Most consistent shop: 1
Lowest standard deviation: 177.53543934162053

Shop means with keepdims=True:
[[[286.12222222]]

 [[274.77777778]]

 [[267.35555556]]

 [[270.62222222]]]
Shape: (4, 1, 1)

Mean-centered sales shape:
(4, 30, 3)

Mean of centered sales for each shop:
[ 1.38950579e-14  5.68434189e-15 -1.26318709e-15  1.64214321e-14]
