Stretch 

In [1]:
# 1. Implement a moving average over a 1D array without loops. (Search: numpy convolve, or cumulative sums.)

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])

window = 3

moving_avg = np.convolve(
    arr,
    np.ones(window) / window,
    mode="valid"
)

print("Original:", arr)
print("Moving average:", moving_avg)

Original: [10 20 30 40 50 60 70]
Moving average: [20. 30. 40. 50. 60.]


In [4]:
# 3. Compare memory: sys.getsizeof a Python list of a million ints versus the equivalent NumPy array. Explain the gap.

import sys
import numpy as np

n = 1_000_000

python_list = list(range(n))
numpy_array = np.arange(n)

print("Python list:", sys.getsizeof(python_list), "bytes")
print("NumPy array:", sys.getsizeof(numpy_array), "bytes")
print("NumPy data:", numpy_array.nbytes, "bytes")

Python list: 8000056 bytes
NumPy array: 8000112 bytes
NumPy data: 8000000 bytes


In [6]:
# 4. Learn np.einsum. Use it for a dot product and a matrix multiply. When is it worth the extra complexity?

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot = np.einsum("i,i->", a, b)

print(dot)

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = np.einsum("ij,jk->ik", A, B)

print(result)

32
[[19 22]
 [43 50]]


In [ ]:
# 5.  Find out what a 'strided view' is. Why can NumPy reverse an array with [::-1] without copying anything?

arr = np.array([10, 20, 30, 40, 50])

reversed_arr = arr[::-1]

print(reversed_arr)

print(reversed_arr.base is arr)

# ---------------------------------- 

reversed_arr = arr[::-1]

reversed_arr[0] = 999

print(arr)
print(reversed_arr)

[50 40 30 20 10]
True
[ 10  20  30  40 999]
[999  40  30  20  10]
